// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package eventstore

import (
	"encoding/json"

	"github.com/google/uuid"
)

type EventStore struct {
	EventID      uuid.UUID       `json:"event_id"`
	AggregateID  uuid.UUID       `json:"aggregate_id"`
	EventType    string          `json:"event_type"`
	EventVersion int32           `json:"event_version"`
	EventData    json.RawMessage `json:"event_data"`
	EventTime    int64           `json:"event_time"`
}

type SnapshotStore struct {
	SnapshotID      uuid.UUID       `json:"snapshot_id"`
	AggregateID     uuid.UUID       `json:"aggregate_id"`
	SnapshotVersion int32           `json:"snapshot_version"`
	SnapshotData    json.RawMessage `json:"snapshot_data"`
	SnapshotTime    int64           `json:"snapshot_time"`
}
