// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package auth_repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
)

type Token struct {
	UserID           uuid.UUID             `json:"user_id"`
	AccessTokenID    uuid.UUID             `json:"access_token_id"`
	AccessExpiresAt  time.Time             `json:"access_expires_at"`
	RefreshTokenID   uuid.UUID             `json:"refresh_token_id"`
	RefreshExpiresAt time.Time             `json:"refresh_expires_at"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        sql.NullTime          `json:"updated_at"`
	Metadata         pqtype.NullRawMessage `json:"metadata"`
}

type User struct {
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	Verified  bool         `json:"verified"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Verification struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	VerificationType string    `json:"verification_type"`
	Email            string    `json:"email"`
	OtpHash          []byte    `json:"otp_hash"`
	CreatedAt        time.Time `json:"created_at"`
	ExpiresAt        time.Time `json:"expires_at"`
}
