// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package auth_repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Clean up expired tokens
	CleanUpTokens(ctx context.Context) error
	// Clean up expired verifications
	CleanUpVerifications(ctx context.Context) error
	// Store or update a user
	CreateUser(ctx context.Context, email string) (uuid.UUID, error)
	// Delete a token by access token ID
	DeleteTokenByAccessTokenID(ctx context.Context, accessTokenID uuid.UUID) error
	// Delete a token by refresh token ID
	DeleteTokenByRefreshTokenID(ctx context.Context, refreshTokenID uuid.UUID) error
	// Delete all tokens for a user
	DeleteTokensByUserID(ctx context.Context, userID uuid.UUID) error
	// Delete a user by ID
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	// Delete a verification by ID
	DeleteVerificationByID(ctx context.Context, id uuid.UUID) error
	// Find a token by access token ID
	FindTokenByAccessTokenID(ctx context.Context, accessTokenID uuid.UUID) (Token, error)
	// Find a token by ID
	FindTokenByID(ctx context.Context, id uuid.UUID) (Token, error)
	// Find a token by refresh token ID
	FindTokenByRefreshTokenID(ctx context.Context, refreshTokenID uuid.UUID) (Token, error)
	// Find a user by email
	FindUserByEmail(ctx context.Context, email string) (User, error)
	// Find a user by ID
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Find a verification by ID
	FindVerificationByID(ctx context.Context, id uuid.UUID) (Verification, error)
	// Refresh a token
	RefreshToken(ctx context.Context, arg RefreshTokenParams) error
	// Store or update a user's verification code.
	StoreOrUpdateVerification(ctx context.Context, arg StoreOrUpdateVerificationParams) (uuid.UUID, error)
	// Store a token
	StoreToken(ctx context.Context, arg StoreTokenParams) error
	// Update a user's email by ID
	UpdateUserEmailByID(ctx context.Context, arg UpdateUserEmailByIDParams) error
	// Update a user's verification status by ID
	UpdateUserVerificationStatusByID(ctx context.Context, arg UpdateUserVerificationStatusByIDParams) error
}

var _ Querier = (*Queries)(nil)
