version: '3'
services:
  golang:
    image: golang:1.19
    restart: unless-stopped
    ports:
    - 8080:8080
    depends_on:
      # - rabbitmq
      - redis
    links:
      # - rabbitmq
      - redis
    volumes:
    - .:/app
    - $HOME/go/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run .

  # rabbitmq:
  #   image: rabbitmq:3.7
  #   restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379