version: '3'
services:
  app:
    image: golang:1.19
    restart: unless-stopped
    ports:
    - 8080:8080
    depends_on:
      - redis
    links:
      - redis
    volumes:
    - ../../../:/app
    - $HOME/go/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go run ./pkg/cqrs/_example/cmd/main.go

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379