// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks_mail

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// AuthUserEmailSender is an autogenerated mock type for the authUserSender type
type AuthUserEmailSender struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, email, verificationID, otp
func (_m *AuthUserEmailSender) SendEmail(ctx context.Context, email string, verificationID uuid.UUID, otp string) error {
	ret := _m.Called(ctx, email, verificationID, otp)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, string) error); ok {
		r0 = rf(ctx, email, verificationID, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAuthUserEmailSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthUserEmailSender creates a new instance of AuthUserEmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthUserEmailSender(t mockConstructorTestingTNewAuthUserEmailSender) *AuthUserEmailSender {
	mock := &AuthUserEmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
